# Gradle
org.gradle.jvmargs=-Xmx2048M -Xms512M
org.gradle.parallel=true
org.gradle.daemon=true

# Minecraft
minecraft_version=1.20.1
minecraft_version_range=>=1.20.0 <=1.20.1

# Fabric
loader_version=0.15.11
loader_version_range=>=0.15.0

# Fabric API
fabric_api_version=0.92.0+1.20.1
fabric_api_version_range=>=0.92.0

# Mod
mod_id=autohook
mod_version=1.0.0
mod_name=AutoHook
maven_group=com.aniblaze
archives_base_name=autohook
