#Tokyo Ghoul Mod Configuration
#Sun Jun 21 22:03:17 EET 2026
ghoul_spawn_chance=15
max_rc=1000000
kakugan_speed_bonus=0.20
kakugan_damage_bonus=0.20
kakuja_rc=1000000
max_blood=1000
stage_4_rc=250000
rc_lost_on_death=0.15
stage_3_rc=50000
stage_2_rc=10000
